debug: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/development
    username: user
    password: pass
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
