debug: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/development
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: /api
