@startuml UserBuilder
class User <<Entity>> {
  -id : UUID
  -username : String
  -password : String
  +User(Builder)
  {static} +builder() : Builder
}

class Builder {
  +username(String) : Builder
  +password(String) : Builder
  +build() : User
}

User *--> Builder
@enduml
